remote_theme: pmarsceill/just-the-docs
logo: "/assets/images/Qlik-Logo_RGB.png"
markdown: kramdown
aux_links:
  "Diagnostic Toolkit":
    - "//diagnostictoolkit.qlik-poc.com"
  "EA Powertools":
    - "//github.com/eapowertools"
  "Qlik Help":
    - "//help.qlik.com"
footer_content: "Qlik Enterprise Architecture, Americas"
